spring:
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

eureka:
  instance:
    metadata-map:
      zone: ru-1
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

ribbon:
  eureka:
    enabled: true